# -*- coding: utf-8 -*-
"""ParentPal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RtsrY4hDLMAwQGGtuIqD5oXNzIQFUV58
"""

import pandas as pd
import numpy as np

malnutrition = pd.read_csv('malnutri.csv')

malnutrition.head()

import sklearn
from sklearn.model_selection import train_test_split

#split atribut dan label
X = malnutrition[['Sex', 'Age', 'Height', 'Weight']]
y = malnutrition['Status']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

# menghitung panjang/jumlah data pada x_test
len(x_test)
print(x_test.shape)
print(y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

#Logistic Regression
model = LogisticRegression()
model.fit(x_train, y_train)
prediction = model.predict(x_test)
print('Accuracy: ', metrics.accuracy_score(prediction, y_test))

#Confusion matrix
from sklearn.metrics import confusion_matrix,classification_report
confusion_mat = confusion_matrix(y_test,prediction)
print("Confusion matrix: \n",confusion_mat)
print(classification_report(y_test,prediction))

model.predict([[0, 5, 74, 11]])